--liquibase formatted sql
--changeset lcrook:000-1
DELETE FROM broadleaf.BLC_PRODUCT_ATTRIBUTE
WHERE PRODUCT_ATTRIBUTE_ID IS NOT NULL;

--changeset lcrook:000-2
DELETE FROM broadleaf.BLC_PRODUCT_FEATURED
WHERE FEATURED_PRODUCT_ID IS NOT NULL;

--changeset lcrook:000-3
DELETE FROM broadleaf.BLC_PRODUCT_OPTION_XREF
WHERE PRODUCT_OPTION_XREF_ID IS NOT NULL;

--changeset lcrook:000-4
DELETE FROM broadleaf.BLC_SKU_OPTION_VALUE_XREF
WHERE SKU_OPTION_VALUE_XREF_ID IS NOT NULL;

--changeset lcrook:000-5
DELETE FROM broadleaf.BLC_PRODUCT_OPTION_VALUE
WHERE PRODUCT_OPTION_VALUE_ID IS NOT NULL;

--changeset lcrook:000-6
DELETE FROM broadleaf.BLC_PRODUCT_OPTION
WHERE PRODUCT_OPTION_ID IS NOT NULL;

--changeset lcrook:000-7
DELETE FROM broadleaf.BLC_SKU_ATTRIBUTE
WHERE SKU_ATTR_ID IS NOT NULL;

--changeset lcrook:000-8
DELETE FROM broadleaf.BLC_SKU_MEDIA_MAP
WHERE SKU_MEDIA_ID IS NOT NULL;

--changeset lcrook:000-9
DELETE FROM broadleaf.BLC_CATEGORY_PRODUCT_XREF
WHERE CATEGORY_PRODUCT_ID IS NOT NULL;

--changeset lcrook:000-10
UPDATE broadleaf.BLC_SKU
SET DEFAULT_PRODUCT_ID=NULL 
WHERE SKU_ID IS NOT NULL;

--changeset lcrook:000-11
UPDATE broadleaf.BLC_PRODUCT 
SET DEFAULT_SKU_ID=NULL 
WHERE DEFAULT_SKU_ID IS NOT NULL;

--changeset lcrook:000-12
DELETE FROM broadleaf.BLC_SKU
WHERE SKU_ID IS NOT NULL;

--changeset lcrook:000-13
DELETE FROM broadleaf.BLC_PRODUCT
WHERE PRODUCT_ID IS NOT NULL;

--changeset lcrook:000-14
DELETE FROM broadleaf.BLC_STATIC_ASSET 
WHERE STATIC_ASSET_ID IS NOT NULL;

--changeset lcrook:000-15
DELETE FROM broadleaf.BLC_CAT_SEARCH_FACET_XREF 
WHERE CATEGORY_SEARCH_FACET_ID IS NOT NULL;

--changeset lcrook:000-16
DELETE FROM broadleaf.BLC_CATEGORY_XREF 
WHERE CATEGORY_XREF_ID IS NOT NULL;

--changeset lcrook:000-17
DELETE FROM broadleaf.BLC_CAT_SITE_MAP_GEN_CFG 
WHERE ROOT_CATEGORY_ID != 2001;

--changeset lcrook:000-18
DELETE FROM broadleaf.BLC_CATEGORY
WHERE CATEGORY_ID != 2001;

--changeset lcrook:000-19
DELETE FROM broadleaf.BLC_CMS_MENU_ITEM
WHERE MENU_ITEM_ID != 1;

--changeset lcrook:000-20
DELETE FROM broadleaf.BLC_SEARCH_FACET
WHERE SEARCH_FACET_ID = 2;
DELETE FROM broadleaf.BLC_INDEX_FIELD_TYPE 
WHERE INDEX_FIELD_TYPE_ID = 3;
DELETE FROM broadleaf.BLC_INDEX_FIELD 
WHERE INDEX_FIELD_ID = 2;
DELETE FROM broadleaf.BLC_FIELD 
WHERE FIELD_ID = 2;